services:
  main-app:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: hacaton-app
    ports:
      - '8000:8000'
    command: 'sh /entrypoint.sh'
    env_file:
      - ../backend/.env
    volumes:
      - ..:/app/
